# Generated by Django 2.2.2 on 2019-07-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0026_auto_20190725_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie_Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=193)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.Data')),
            ],
        ),
    ]
